---
- name: Copy a file from local machine to remote host
  hosts: all
  become: yes  # 以 root 权限执行操作
  tasks:
    - name: Copy file to /root/time directory
      copy:
        src: singlehost_report_generator.sh  # 本地文件路径
        dest: /opt/ltp-install           # 目标路径
        mode: '777'                      # 设置文件权限
